local icons = {
  ghost = '',
  cosmic = '💫',
  star = '★',
  scorpio = '♏︎',
  rocket = '🚀',
  warn = '',
  info = '',
  error = '',
  hint = '',
  perf = ' ',
  note = '',
  branch = '',
  file = '',
  dotdotdot = '…',
  information = '',
  symlink = '',
  line_number = '',
  debug = ' ',
  flame = ' ',
  check = ' ',
  trace = '✎',
  file1 = '',
  file2 = '',
  clock = '',
  word = '',
  diff_add = '',
  diff_modified = '',
  diff_remove = '',
  distro= {
    arch = '󰣇',
    alpine = '󰣖',
    centos = '󱄚',
    debian = '',
    fedora = '',
    freebsd = '',
    suse = '',
  }
}

return icons
