return {
  {
    "windwp/nvim-ts-autotag",
    event = "VeryLazy",
    opts = {
      enable = true,
      enable_rename = true,
      filetypes = {
        "astro",
        "ejs",
        "eta",
        "glimmer",
        "handlebars",
        "hbs",
        "htm",
        "html",
        "javascript",
        "javascriptreact",
        "jsx",
        "markdown",
        "php",
        "rescript",
        "svelte",
        "tsx",
        "typescript",
        "typescriptreact",
        "vue",
        "xml",
      },
    },
  },
}
